version: "3.8"

services:
  api:
    container_name: goAPI
    build: ./go/
    tty: true
    volumes:
      - ./go/goAPIs
    ports:
      - "8085:80"
    depends_on:
      -  mysql

  mysql:
    container_name: mysqlDB
    build: ./mysql/
    env_file:  ./mysql/.env
    environment:
      MYSQL_DATABASE: CAtech
      TZ: "Asia/Tokyo"
    volumes:
      - /mysql/init:/docker-entrypoint-initdb.d
      - DB-data:/var/lib/mysql
      - /mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  DB-data:





